name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "registry.docker.w4w.cc"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "registry.docker.w4w.cc"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "registry.docker.w4w.cc", custom_domain = true },
  { pattern = "quey.registry.docker.w4w.cc", custom_domain = true },
  { pattern = "gcr.registry.docker.w4w.cc", custom_domain = true },
  { pattern = "k8s-gcr.registry.docker.w4w.cc", custom_domain = true },
  { pattern = "k8s.registry.docker.w4w.cc", custom_domain = true },
  { pattern = "ghcr.registry.docker.w4w.cc", custom_domain = true },
  { pattern = "cloudsmith.registry.docker.w4w.cc", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.registry.docker.w4w.cc", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
